# Utiliza una imagen base de OpenJDK
FROM openjdk:17-jdk-slim

# Copia el archivo JAR construido al contenedor
COPY target/animalshelter-0.0.1-SNAPSHOT.jar /app/animalshelter.jar

# Establece el directorio de trabajo
WORKDIR /app

# Expone el puerto en el que la aplicación escuchará
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "animalshelter.jar"]
